# This workflow will install Python dependencies, run tests, format, and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Mapillary Python SDK - PyTest Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip && make setup-dev && pip install flake8 black pytest requests mercantile vt2geojson pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Locally install branch's mapillary
      run: |
        make build
    - name: Formatting with black
      run: |
        make format
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with pytest
      run: |
        pip freeze && make local-install && pip freeze && make test
